show_watermark_in_background:
  default: true
  description: 
    en: "If enabled will generate and display a watermark on the page."
    pt_BR: "Se ativado irá gerar e exibir uma marca d'água na página."
    zh_CN: "在页面上显示水印"

scroll_enabled:
  default: true
  type: bool
  description: 
    en: "If enabled the watermark will be scrolled with the page."
    pt_BR: "Se ativado a marca d'água irá acompanhar a rolagem da página."
    zh_CN: "水印会跟随页面滚动"

only_in_categories:
  default: ""
  type: list
  list_type: category
  description: 
    en: "List of categories in which the watermark should be displayed."
    pt_BR: "Lista de categorias em que a marca d'água deve ser exibida."
    zh_CN: "需要显示水印的类别"

except_in_categories:
  default: ""
  type: list
  list_type: category
  description: 
    en: "List of categories in which the watermark should not be displayed."
    pt_BR: "Lista de categorias em que a marca d'água não deve ser exibida."
    zh_CN: "不显示水印的类别"

only_in_tags:
  default: ""
  type: list
  list_type: tag
  description: 
    en: "List of tags in which the watermark should be displayed."
    pt_BR: "Lista de tags em que a marca d'água deve ser exibida."
    zh_CN: "需要显示水印的标签"

except_in_tags:
  default: ""
  type: list
  list_type: tag
  description: 
    en: "List of tags in which the watermark should not be displayed."
    pt_BR: "Lista de tags em que a marca d'água não deve ser exibida."
    zh_CN: "不显示水印的标签"

if_site_title_matches:
  default: ""
  type: string
  description:
    en: "Display watermark only if site title matches this regular expression."
    pt_BR: "Exibir marca d'água somente se o título do site corresponder a essa expressão regular."
    zh_CN: "当站点标题满足这个正则时显示水印"

or_if_url_matches:
  default: ""
  type: list
  description:
    en: "OR display the watermark if url matches any of the regular expressions in the list. Note that the URL tested does not include the hostname."
    pt_BR: "OU exiba a marca d'água se a URL corresponder a qualquer expressão regular na lista. Observe que a URL testada não inclui o nome de dominio."
    zh_CN: "或者，当站点URL满足这个正则时显示水印。注意，用来测试的URL不包含主机名。"

tile_width:
  default: 220
  min: 0
  type: integer  
  description: 
    en: "The width (in px) of the tile that contains the watermark information."
    pt_BR: "O comprimento (em px) do bloco que contém a informação da marca d'água."
    zh_CN: "包含水印信息的方片宽度（px）"

tile_height:
  default: 220
  min: 0
  type: integer  
  description: 
    en: "The height (in px) of the tile that contains the watermark information."
    pt_BR: "A altura (em px) do bloco que contém a informação da marca d'água."
    zh_CN: "包含水印信息的方片高度（px）"

color:
  default: "var(--primary-low)"
  type: string
  description: 
    en: "The color of the watermark text."
    pt_BR: "A cor do texto na marca d'agua."
    zh_CN: "水印文本的颜色"

text_align:
  default: center
  type: enum
  choices:
    - left
    - center
    - right
  description: 
    en: "How the text should be aligned relative to x,y coordinates when drawn."
    pt_BR: "Como o texto deve ser alinhado em relação as coordenadas x,y quando desenhado."
    zh_CN: "绘制文本时，相对 x、y 坐标的对齐方向"

text_rotation:
  default: -45
  min: -90
  max: 90
  type: integer  
  description: 
    en: "The angle in which the text should be rotated relative to x,y coordinates when drawn."
    pt_BR: "O ângulo em que o texto deve ser rotacionado em relação as coordenadas x,y quando desenhado."
    zh_CN: "绘制文本时，相对 x、y 坐标的旋转角度"

display_text: 
  default: ""
  type: string
  description: 
    en: "Text to be rendered in the watermark."
    pt_BR: "Texto para ser renderizado na marca d'água."
    zh_CN: "水印中渲染的文本"

display_text_font:
  default: "bolder 1rem var(--font-family)"
  type: string
  description: 
    en: "The font used to render the text (parsed as CSS font value)."
    pt_BR: "A fonte usada para renderizar o texto (intepretado com um valor da propriedade font em CSS)."
    zh_CN: "渲染文本的字体（解析为 CSS 字体值）"

display_text_x:
  default: 0
  type: integer    
  description: 
    en: "The x-axis coordinate of the point at which to begin drawing the text in the tile canvas, in pixels."
    pt_BR: "A coordenada no eixo x para o ponto em que o texto deve ser desenhado no canvas do bloco, em pixels."
    zh_CN: "在方片画布中绘制文本时，x 轴坐标的起点（px）"

display_text_y:
  default: 116
  type: integer    
  description: 
    en: "The y-axis coordinate of the point at which to begin drawing the text in the tile canvas, in pixels."
    pt_BR: "A coordenada no eixo y para o ponto em que o texto deve ser desenhado no canvas do bloco, em pixels."
    zh_CN: "在方片画布中绘制文本时，y 轴坐标的起点（px）"

display_username:
  default: true
  type: bool
  description: 
    en: "If enabled the watermark will render the current username."
    pt_BR: "Se ativado a marca d'água irá renderizar o código do usuário."
    zh_CN: "水印中渲染当前的用户名"

display_username_font:
  default: "bolder 2rem var(--font-family)"
  type: string
  description: 
    en: "The font used to render the username (parsed as CSS font value)."
    pt_BR: "A fonte usada para renderizar o código do usuário (intepretado com um valor da propriedade font em CSS)."
    zh_CN: "渲染当前用户名的字体（解析为 CSS 字体值）"

display_username_x:
  default: 0
  type: integer    
  description: 
    en: "The x-axis coordinate of the point at which to begin drawing the username in the tile canvas, in pixels."
    pt_BR: "A coordenada no eixo x para o ponto em que o código do usuário deve ser desenhado no canvas do bloco, em pixels."
    zh_CN: "在方片画布中绘制用户名时，x 轴坐标的起点（px）"

display_username_y:
  default: 140
  type: integer    
  description: 
    en: "The y-axis coordinate of the point at which to begin drawing the username in the tile canvas, in pixels."
    pt_BR: "A coordenada no eixo y para o ponto em que o código do usuário deve ser desenhado no canvas do bloco, em pixels."
    zh_CN: "在方片画布中绘制用户名时，y 轴坐标的起点（px）"

display_timestamp:
  default: true
  type: bool
  description: 
    en: "If enabled the watermark will render the timestamp the page was rendered."
    pt_BR: "Se ativado a marca d'água irá renderizar o dia/horário em que a página foi renderizada."
    zh_CN: "水印中渲染时戳"

display_timestamp_format:
  default: ""
  type: string
  description: 
    en: "How the timestamp will be formatted. For information about the valid formats, please refer to https://momentjs.com/docs/#/displaying/."
    pt_BR: "Como o dia/horário deve ser formatado. Para informações osbre os formatos válidos, por favor consulte https://momentjs.com/docs/#/displaying/."
    zh_CN: "时戳格式（访问 https://momentjs.com/docs/#/displaying/ 查询可用格式）"

display_timestamp_font:
  default: "bolder 1rem var(--font-family)"
  type: string
  description: 
    en: "The font used to render the timestamp (parsed as CSS font value)."
    pt_BR: "A fonte usada para renderizar o dia/horário (intepretado com um valor da propriedade font em CSS)."
    zh_CN: "渲染时戳的字体（解析为 CSS 字体值）"

display_timestamp_x:
  default: 0
  type: integer    
  description: 
    en: "The x-axis coordinate of the point at which to begin drawing the timestamp in the tile canvas, in pixels."
    pt_BR: "A coordenada no eixo x para o ponto em que a data/horário deve ser desenhada no canvas do bloco, em pixels."
    zh_CN: "在方片画布中绘制时戳时，x 轴坐标的起点（px）"

display_timestamp_y:
  default: 164
  type: integer    
  description: 
    en: "The y-axis coordinate of the point at which to begin drawing the timestamp in the tile canvas, in pixels."
    pt_BR: "A coordenada no eixo y para o ponto em que a data/horário deve ser desenhada no canvas do bloco, em pixels."
    zh_CN: "在方片画布中绘制时戳时，y 轴坐标的起点（px）"
